let photoIntro;
export default photoIntro = {
  v: "5.7.6",
  fr: 60,
  ip: 0,
  op: 300,
  w: 1920,
  h: 1080,
  nm: "270_photo_intro",
  ddd: 0,
  assets: [
    {
      id: "image_0",
      w: 1000,
      h: 1000,
      u: "",
      p: "",
      e: 0,
    },
    {
      id: "comp_0",
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 3,
          nm: "CTRL_PHOTO",
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.2, y: 1 },
                  o: { x: 0.4, y: 0 },
                  t: 4,
                  s: [421, 548.5, 0],
                  to: [0, -4.5, 0],
                  ti: [0, 4.5, 0],
                },
                { t: 34, s: [421, 521.5, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
            s: {
              a: 1,
              k: [
                {
                  i: { x: [0.15, 0.15, 0.833], y: [1, 1, 1] },
                  o: { x: [0.4, 0.4, 0.4], y: [0, 0, 0] },
                  t: 4,
                  s: [0, 0, 100],
                },
                { t: 28, s: [100, 100, 100] },
              ],
              ix: 6,
              l: 2,
            },
          },
          ao: 0,
          ip: 0,
          op: 780,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 4,
          nm: "MASK 2",
          td: 1,
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [420.73, 509.22, 0], ix: 2, l: 2 },
            a: { a: 0, k: [418.73, 117.22, 0], ix: 1, l: 2 },
            s: {
              a: 1,
              k: [
                {
                  i: { x: [0.2, 0.2, 0.833], y: [1, 1, 1] },
                  o: { x: [0.4, 0.4, 0.4], y: [0, 0, 0] },
                  t: 4,
                  s: [0, 0, 100],
                },
                { t: 28, s: [100, 100, 100] },
              ],
              ix: 6,
              l: 2,
            },
          },
          ao: 0,
          shapes: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [0, 0],
                      ],
                      o: [
                        [0, 0],
                        [0, 0],
                        [0, 0],
                        [0, 0],
                      ],
                      v: [
                        [418.73, 433],
                        [99.95, 114.22],
                        [418.73, -1164.56],
                        [737.51, 114.22],
                      ],
                      c: true,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "fl",
                  c: {
                    a: 0,
                    k: [0.109803921569, 0.337254901961, 0.419607843137, 1],
                    ix: 4,
                  },
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  bm: 0,
                  nm: "Fill 1",
                  mn: "ADBE Vector Graphic - Fill",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Group 1",
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
          ],
          ip: 0,
          op: 918,
          st: 28,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 0,
          nm: "PHOTO",
          parent: 1,
          tt: 1,
          refId: "comp_1",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [-24.574, 0, 0], ix: 2, l: 2 },
            a: { a: 0, k: [488.426, 574.567, 0], ix: 1, l: 2 },
            s: { a: 0, k: [84, 84, 100], ix: 6, l: 2 },
          },
          ao: 0,
          w: 1000,
          h: 1000,
          ip: 0,
          op: 908,
          st: 0,
          bm: 0,
        },
      ],
    },
    {
      id: "comp_1",
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 2,
          nm: "Cipher.png",
          cl: "png",
          refId: "image_0",
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [500, 500, 0], ix: 2, l: 2 },
            a: { a: 0, k: [500, 500, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 908,
          st: 0,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 0,
      nm: "Pre-comp 12",
      refId: "comp_0",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          a: 1,
          k: [
            {
              i: { x: 0.2, y: 1 },
              o: { x: 0.6, y: 0 },
              t: 52,
              s: [656.8, 603.36, 0],
              to: [-20.32, 0, 0],
              ti: [20.32, 0, 0],
            },
            { t: 78, s: [534.88, 603.36, 0] },
          ],
          ix: 2,
          l: 2,
        },
        a: { a: 0, k: [414, 452, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 828,
      h: 904,
      ip: 10,
      op: 928,
      st: 10,
      bm: 0,
    },
  ],
  markers: [],
};
